### ISSUE TITLE
optimizing megalodon GPU utilization on computing cluster

### ISSUE THREAD

**Issue by mollybrothers** [nanoporetech/megalodon#153]
This is potentially a bit outside of megalodon's scope, but I have been having a lot of trouble with megalodon being very slow and (I think) way underutilizing the GPU.

I am using a computing cluster, the GPU is an nVIDIA GTX 1080Ti (unfortunately the best available I can use at the moment!). 

On current run, reads are N50 of 8.5kb, and being processed at less than 2 reads/sec, 9.91e+4 samples/sec. nvidia-smi output (mine is the one on GPU no.2) shows 0% GPU utilization and is not getting close to memory max. I understand that this may be an input/output issue, but I am not sure how to diagnose it properly. The input queue is always above 0% and does get up to 100%, and the output queue never gets above a couple %, so my thought is this is not the issue.

If there are any outputs that would be helpful, let me know and I can share them (some are too big to attach to this post, like the log.txt file). I know there are bunch of parameters in megalodon that I might be able to tweak, but if you have any suggestions I would be very grateful!

Thanks, Marcus!

![image](https://user-images.githubusercontent.com/31557235/121216696-00ac1980-c836-11eb-8c50-ac500aee52ff.png)

P.S. I am planning on updating guppy (can't get up to version 5, as cluster doesn't have CUDA 11 available...) and megalodon soon, haven't done that yet (always afraid to install new things and break my analysis pipeline!!). I am currently running guppy 4.2.2 and megalodon 2.2.10

**Comment by marcus1487** [comment]
I would definitely recommend upgrading to a newer version of megalodon. Some recent changes should be much more robust to different run conditions and keep the queue of reads supplied to guppy full (and thus using GPUs).

For the steps to diagnose the I/O issue I would recommend just watching the IO queue status from megalodon on the command line. If the extract_signal queue remains empty for the majority of the run then megalodon is waiting on reading data from disk. This can be addressed with the `--num-read-enumeration-threads` and `--num-extract-signal-processes` arguments (these likely have different names or didn't exist in previous versions of megalodon). The other point to note is that signal extraction is much faster from multi-FAST5 than single-FAST5 format, so I would recommend this conversion for speed increases. Let me know if none of these seem to be the issue.

**Comment by mollybrothers** [comment]
Tried updating megalodon today to 2.3.3 and I keep getting an error very soon after connecting to the guppy server and starting to extract reads:

ERROR: get_fast5_file() got an unexpected keyword argument 'driver'

I have attached log.txt and the guppy log as well if those help. I am not sure how to fix this!

[log.txt](https://github.com/nanoporetech/megalodon/files/6633980/log.txt)
[guppy_basecall_server_log-2021-06-10_12-35-01.log](https://github.com/nanoporetech/megalodon/files/6633981/guppy_basecall_server_log-2021-06-10_12-35-01.log)

**Comment by marcus1487** [comment]
It looks like your ont_fast5_api is out of date. Try upgrading this (`pip install -U ont_fadt5_api`). It should solve this issue.

**Comment by mollybrothers** [comment]
This might just be peculiarities of our campus's computing cluster and thus unsolvable here, but the analysis has slowed down again to <2 reads/sec / <2e+5 samples/s. nvidia-smi has a utilization of >90%, though, so perhaps this is as good as this GPU can do?

The extract_signal queue gets up close to 100% early on and stays that way, and the output queue never goes above a few percent, so it would seem that I/O is not an issue.

My input fast5 files _are_ multi-fast5.

I am often running multiple megalodon jobs at once – and I thought maybe that might be the problem, but even running a single job alone has these slow read processing speeds.

**Comment by mollybrothers** [comment]
Since updating, I've also gotten (seemingly random, doesn't happen every time) guppy server timeout errors and this error:

`Send read read malformed error "Something went wrong, read dict might be malformed. return_code: result.failed"`

Sometimes this happens after megalodon has been running for a few hours and then the rest of the reads will have either a server timeout error or the above error. And if I have multiple megalodon instances running, they will all fail this way at the same time.

**Comment by marcus1487** [comment]
This looks like the guppy server is likely overloaded. I would not suggest running multiple megalodon or guppy instances on the same GPU at the same time. Generally the same performance should be achievable by making these runs in serial. I'm not sure how your server manages resources, but it might also be worth checking if there are zombie guppy servers running which could be draining resources.

**Comment by mollybrothers** [comment]
I do not run them on the same GPU ever – always separate runs on separate GPUs in parallel. And even just doing a single run gives me this issue lately.

Perhaps zombie guppy servers could explain all of these issues. I can talk to the IT helpdesk at our cluster and see if there is a way they can find these (I don't think I have access to nodes unless I'm running jobs on them). But if this turns out to be a problem, is there a way to prevent zombie processes on my end so I don't have to bother the help desk each time?

**Comment by marcus1487** [comment]
Megalodon is relatively safe with respect to closing the guppy servers opened, but certain edge cases (e.g. being killed by the OS/job scheduler or before initialization completes) may bypass these safeguards. It is a bit odd that the instances are killed at the same time when the guppy servers should be separate. Are these runs using a system guppy install?

**Comment by mollybrothers** [comment]
They are using a guppy install in my user directory, not on the entire system. So I specify the path to the guppy server, which is in a subdirectory of my home directory. If installing on the system is something you think might help, I can request that from IT support.

**Comment by marcus1487** [comment]
I've seen issues the other way around (where a system install causes issues). For the runs killed by out of time I would hope that the job scheduler would kill all started processes.

Are these jobs run on the same node? Could it be a memory error that kills all the jobs simultaneously? It would be quite odd for all of the megalodon/guppy jobs to fail simultaneously from different nodes.

**Comment by mollybrothers** [comment]
I would think the same, that running out of time should appropriately kill everything.

At most, there are 2 on the same node, but they are mostly on different nodes. I should clarify – 'same time' is not _exactly_ the same time. For example, 5 jobs all started ~same time 'completed' within the same 15 minutes, all with logs that looked like the latest ones I posted above.

For all the time I've been using megalodon, I have never run into any of these above issues before, so I am as perplexed as you are! For now, I'll see if IT support can find any zombie processes (based on your answer, there probably are not any). I'll keep you updated.

**Comment by marcus1487** [comment]
I had another look at your latest logs and it looks like the megalodon log (`log.txt`) file may not have been posted. Would you mind posting a link to that again?

**Comment by mollybrothers** [comment]
Sorry about that, looks like I mixed up my files a bit. This is not from the same exact run as the guppy log posted above, but it has the same errors/issues disconnecting from the server.

[log.txt](https://drive.google.com/file/d/1OqT3BcbOokFU5mCaj8687ZrNGi3Flv8J/view?usp=sharing)

**Comment by marcus1487** [comment]
I've just pushed a fix that should help in this situation. I do think that upgrading to a newer version of guppy should help, but understand the cuda version issue. This fix will stop running through so many reads when the guppy client-server connection breaks. So you may still see some of these errors, but it should be far fewer and give the server a chance to recover and re-establish a connection to the server.

**Comment by mollybrothers** [comment]
re-install from github did not seem to help all that much, still getting a large number of reads having the server connection issue.  This is quite odd, as I have been running megalodon for a while now on the cluster and have never had an issue like this before. And I definitely am now thinking it is nothing to do with megalodon and everything to do with the campus's cluster.

I was thinking...when I run guppy on its own, it doesn't seem to have a connection or speed issue. Is there any way to run a rerio model (I'm using the all-context model) with guppy alone and then use megalodon to get aggregated (.bed) and per-read data (.txt)? Or some other way to get around the guppy server for megalodon? The only issue (potentially) is that I have barcoded data and would need them to be separated for analysis.

Thanks so much for all the help and suggestions, I really appreciate it.

**Comment by marcus1487** [comment]
Megalodon can use the FAST5 output from guppy (with the `--post_out` option), but this is not likely to help here as this option generally slows guppy performance by an order of magnitude (slowed by disk write and HDF5 overhead). This also results in FAST5 files that are ~10X the size of the raw data. This was added as an option before the direct guppy python interface was implemented. This is not a recommended solution, but wanted to mention since it is relevant (see `--do-not-use-guppy-server` argument in `megalodon --help-long`).

It is a bit odd that guppy alone does not suffer and disconnects or failed reads on the same environment (would be good to confirm this by looking at the number of failed reads from a direct guppy run). As for a solution which runs guppy followed by megalodon (without re-running the basecalling), we are working on solution for this, but don't have one at the moment. The issue is that megalodon needs access to the neural network output. As noted above this can be stored in a FAST5, but is not a realistic solution in most cases.

Guppy does have the ability to output modified base scores into an unmapped bam file containing a custom tag to hold the modified base scores. But since these scores are computed differently than in megalodon and against the basecalls instead of the reference, the validation performance from these scores is generally much lower. We are working on identifying and addressing these issues, but again don't have the solutions released at the moment.

Since it seems that the server is getting overloaded using megalodon, one thing that might help is to adjust some of the megalodon parameters concerning the feeding of reads to guppy. Namely you might lower the `--guppy-concurrent-reads` value (default `10`), or use fewer `--processes`. Megalodon can often run at the same speed with fewer workers than the number of cores available on a node. It is more about supplying guppy/the GPU with the right amount of data.
